### ISSUE TITLE
checkbox readonly render as hidden input field

### ISSUE THREAD

**Issue by stellalie** [adrianhurt/play-bootstrap#106]
@adrianhurt im not sure if this is a bug or an intended feature but b4.checbox that have options of "readonly" set to true will render correctly as greyed disabled checkbox, however....

it is actually an input type hidden in the actual html.. so regardless whether the box is checked or not... it will get submitted in the form regardless the value in the `checked` field, .ie:

```
@b4.checkbox(multiField("[" + index + "]"),
                '_text -> "value",
                'checked -> false,
                'value -> "test"
)

```
will render input value (label not included), ie:
```
<input type="hidden" name="fieldname[1]" value="somethingelse_nottest">
```

also, another bug if the checkbox is wrapped inside multifield ie. 
`@b4.multifield()(globalArgs, Seq()) { implicit cfc =>`, the `value` is ignored and this confuses me greatly

**Comment by adrianhurt** [comment]
Hi @stellalie. The first one it's an intended feature. You can check it [here](http://adrianhurt.github.io/play-bootstrap/1.4-P26-B4/docs/#helpers-disabled-readonly).

Regarding the bug you say with multifield, could you give me a complete example? Multifield helper is to create your own helper, so I would need to know exactly how it's implemented in order to help you.
