### ISSUE TITLE
fooForm in all the examples

### ISSUE THREAD

**Issue by bharal** [adrianhurt/play-bootstrap#107]
Hi,

just checked the documentation, and this term "fooForm" appears everywhere. 

It isn't clear what "fooForm" does, or how to use it. Can you either use a better name for whatever this thing is, or clearly express what fooForm is in the documentation?

**Comment by mkurz** [comment]
`fooForm` is a Play form object. You should read the Play Framework documentation:
https://www.playframework.com/documentation/2.6.x/ScalaForms#Form-Basics
https://www.playframework.com/documentation/2.6.x/JavaForms#Defining-a-form

**Comment by adrianhurt** [comment]
Thanks @mkurz. `fooForm` it's just the arbitrary name of a simple `Form[A]` object. It's used the same way it's shown at Play Framework docs (as mkurz said). But instead of using concrete examples like `userForm` or `postForm` I opted to use the foo ([https://en.wikipedia.org/wiki/Foobar](https://en.wikipedia.org/wiki/Foobar)) convention, so you can translate it to "myForm",  "whatEverYouWantForm", ...
