### ISSUE TITLE
V4 alpha 5 - Help Block

### ISSUE THREAD

**Issue by dmbuchta** [adrianhurt/play-bootstrap#74]
Looks like the .help-block classes were replaced with .from-text [See here](http://v4-alpha.getbootstrap.com/components/forms/#help-text)

Also, I think for validation purposes (success/warning/danger) they moved from using the help-block entirely to using .form-control-feedback [See here](http://v4-alpha.getbootstrap.com/components/forms/#validation)

**Comment by adrianhurt** [comment]
Thanks @dmbuchta.

I've just released the new SNAPSHOT versions for Bootstrap 4.alpha.5:
* 1.1.1-P24-B3-SNAPSHOT
* 1.1.1-P24-B4-SNAPSHOT
* 1.1.1-P25-B3-SNAPSHOT
* 1.1.1-P25-B4-SNAPSHOT

I will update the docs as well as soon as possible.

I hope I hadn't forgot any other change of this alpha version...

**Comment by dmbuchta** [comment]
Great, thanks! I'm testing it out right now.

**Comment by dmbuchta** [comment]
Hmmm. I'm new to using sbt, will the following pull down the new jar?
`"com.adrianhurt" %% "play-bootstrap" % "1.1-P25-B4" exclude("org.webjars", "jquery")`

I tried `"com.adrianhurt" %% "play-bootstrap" % "1.1.1-P25-B4" exclude("org.webjars", "jquery")`  but it didn't work.

**Comment by adrianhurt** [comment]
Sorry, you need the resolver for SNAPSHOTs

```
// Resolver is needed only for SNAPSHOT versions
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies ++= Seq(
  "com.adrianhurt" %% "play-bootstrap" % "1.1.1-P25-B4-SNAPSHOT"
)
```

**Comment by adrianhurt** [comment]
I've just updated the docs as well

**Comment by dmbuchta** [comment]
Looks good. Any thoughts about adding validation into your repo? 

I'm currently using, https://github.com/1000hz/bootstrap-validator, it works pretty good for the most part. It would be cool if you added it (or something similar) into yours.

**Comment by dmbuchta** [comment]
Just a suggestion :)

**Comment by adrianhurt** [comment]
Hi, it's a good question. But the purpose of this library is simply to render the HTML part, not JavaScript. There are other plugins that do exactly that, like this one.

As I see (after only 2 minutes looking at the docs), you can use __play-bootstrap__ and __bootstrap-validator__ perfectly. The only issue is the block `help-block with-errors` that the validator needs. You can solve it by different ways:

* Create you own _field constructor_ as it is explained on the docs. The you can add that block.
* Using JavaScript, add manually the `with-errors` block just before enable the validation with `$('#myForm').validator()` (instead of using `data-toggle="validator"`, of course)
* I'm sure there are more options…
