### ISSUE TITLE
Can't represent null option in select

### ISSUE THREAD

**Issue by florianschneider** [adrianhurt/play-bootstrap#81]
I have a class (written in java)
```
public class Foo {
      private long internalId;
      private Foo next;
     // accessors
}
```
Now I'm having a form in which I want to select who's next from a set of other `Foo` instances (called `assignableSuccessors` below).

```
@b3.select(fooForm("next.internalId"), 
           options = assignableSuccessors.map(ch => (""+ch.internalId, ch.shortName)),
           '_label -> "foo.next")
```
This way, I'm never able to unset the `next` attribute again using the select. 
Using 

```
@b3.select(fooForm("next.internalId"), 
           options = assignableSuccessors.map(ch => (""+ch.internalId, ch.shortName)),
           '_default -> "Choose who's next",
           '_label -> "foo.next")
``` 
does not really help as this will only lead to a validation error on the form once I choose the default option on the select again and submit the form.

Would be glad if you could provide guidance on this issue.

**Comment by adrianhurt** [comment]
Hi @florianschneider 

Oh, I see I've missed the original functionality of `'_default` argument. It should be disabled in order to use it as a placeholder and a way to force the user to select one. But not for your case of using it as an additional option. Thanks, I will raise an issue for this bug to remember I have to fix it.

If you need another option (an 'empty' one in your case) you need to add it programmatically and process it after validation. For example, you can prepend an option with ("0" -> "None") value.

```
@b3.select(
    fooForm("next.internalId"), 
    options = (("0", "None") +: assignableSuccessors.map(ch => (""+ch.internalId, ch.shortName))),
    '_label -> "foo.next"
)
```

And after validation (or maybe during, depending on your needs) you will set `foo.next` to `null` (if this is de functionality you need).

**Comment by A00107408** [comment]
Happy St. Patricks Day !!

**Comment by florianschneider** [comment]
Thanks @adrianhurt that was exactly the workaround I'm pursuing right now :-)

**Comment by adrianhurt** [comment]
Your welcome. But it's not a workaround. It's the way to do it. `options` parameter is the place to put every option, so if you have an "empty" or "null" option that the user can select, you need to insert it as well within `options` parameter.

I close the issue, but feel free to reopen it if you need it.
