### ISSUE TITLE
bootstrap 4

### ISSUE THREAD

**Issue by Enalmada** [adrianhurt/play-bootstrap#99]
Opening to keep track of things anyone notice need to change.  Good news is I have not noticed much:

beta-1 got rid of column offsets and this makes horizontal form checkboxes go to the far left.  Can be solved manually for now by adding empty label ('_label -> "").  Beta-2 seems to have put them back.

Inline forms perhaps shouldn't have "form-group" wrapping elements.  It seems to mess with the layout in the smallest responsive size (but I have not retested on final release).
   https://getbootstrap.com/docs/4.0/components/forms/#form-groups
   https://getbootstrap.com/docs/4.0/components/forms/#inline-forms

I made a temporary hack that seems to work around this but I am pretty sure it isn't the final fix
https://github.com/Enalmada/play-bootstrap/commit/f46ccbe0c124bf0622ff1ac0e6d7651e35c701a1

 It also looks like they changed the html of custom checkboxes in beta-3 and then again in the final release.  

Possibly the way form validation is styled
   https://getbootstrap.com/docs/4.0/components/forms/#how-it-works

**Comment by stellalie** [comment]
+1 also on fixing bootstrap inline error layout, atm its broken due to few differences

**Comment by mkurz** [comment]
@Enalmada @stellalie Did you notice some other changes in the Bootstrap 4 final release? Just to keep that issue here updated...

**Comment by Enalmada** [comment]
Updated comment with the things I happened to notice: inline form wrapping, custom checkboxes, form validation.  I wasn't sure how to work around the new custom checkbox so I have just continued using the beta.  I will test out any snapshot you want feedback on!

**Comment by adrianhurt** [comment]
Sorry for having this repo outdated (all of them indeed). My last months are being crazy and I don't have enough time to check the new B4. Sorry again. I honestly appreciate your help and I promise this weekend I'll try to check it and publish a new snapshot to try it. Thanks!!

**Comment by mkurz** [comment]
@adrianhurt it's OK - take your time. Whatever happened the last month I hope you are ok!

**Comment by adrianhurt** [comment]
Hi! I've just released the version 1.3.P2{4,5,6}-B{3,4}-SNAPSHOT with bootstrap 4. Please, note it's the first snapshot and I've not already tested properly. But it's a first approach if you want to try it. I hope to update the documentation page during the next week, so meanwhile I put here the main changes and notes:

* Form groups have still support for warning state (although it will be necessary a custom css not provided by this plugin)
* Form groups have still classes "has-danger", "has-success" and "has-warning". Due to it is automatically managed by the plugin, it lets you easily to style the whole form group (such the label as it was previously).
* validation feedback icons have been removed
* You can use 'placeholder for custom file helper 
* Multifield has now the ability of showing the validation states (like errors) independently for each field

As I commented, this is a first release for the snapshot and the work is still in progress. Indeed, the validation needs to have a way to pass feedback texts without the status in its corresponding input for client side validations.

In addition, I'm thinking about adding the parameters "custom" and "feedbackTooltip" directly to field constructors. Then, we will be able to parametrised the field constructor once and not having to do it for each field. In other words, we could have every field as "custom" without indicating it explicitly for each field. It would be similar as it is done now for horizontal forms and their corresponding grid classes.

Please, it would be great if you could test it, and any bug or misunderstanding you see, just let me know.

Thanks!

**Comment by adrianhurt** [comment]
Regarding to validation issue. I was thinking in adding only "is-invalid" class to input automatically when it has some error from server. Otherwise, the user should add manually the "is-valid" and "is-invalid" classes when needed. I think it would be the best solution for handling server and clients sides validation. What do you think?

**Comment by Enalmada** [comment]
Seems good so far from basic testing.  Only thing strange I noticed so far was that with inline forms the custom select puts label on top and the regular select puts label on the left but I think this is a bootstrap issue:

![image](https://user-images.githubusercontent.com/1892132/36917440-b07c121c-1e0b-11e8-8315-f3661e42dc81.png)

**Comment by adrianhurt** [comment]
Sorry @Enalmada, I'll try to check it tomorrow. Meanwhile,  I've just updated version 1.3-P2X-BX-SNAPSHOT.

I noticed the class "form-horizontal" has disappeared and "form-inline" now set that container as flex-box, so it must be placed as the direct wrapper of the form-groups. I.e. you cannot add "form-inline" at the form if you have internal custom wrappers inside a complex form. For that reason, I've decided to remove the classes "form-vertical", "form-horizontal" and "form-inline" from forms. So you will need to add "form-inline" to your inline forms when needed (using 'class argument).

I'm currently updating de docs. I hope I could publish it during this week.

Thanks!

**Comment by adrianhurt** [comment]
@Enalmada, could you try adding the class "form-control" to your example of the custom select (adding to it  `'class -> "form-control"` or directly with inspector in your browser). Maybe I could add it by default for every custom select (or maybe every custom helper…)

**Comment by Enalmada** [comment]
I tried adding "form-control" to custom-select and it fixed the label position but the pulldown icons went missing.  I see a b4 bug https://github.com/twbs/bootstrap/issues/25413 which looks like it may be the reason and it will be fixed in next bootstrap release so I think we can just ignore inline custom-select issue for now.  

For the inline issue, I feel like most people using inline form constructor would want form-inline added automatically.  I wonder if it would be better to have a special field constructor or argument to disable adding "form-inline"?

**Comment by adrianhurt** [comment]
Ok about the custom select's issue. Regarding to "form-inline", I thought exactly the same (adding a way to disable it). But I think it's more easy to understand that "form-inline" class must be exactly on form-group's parent container. I know 95% of the cases we would need to add it on inline forms, but it's more clear, and specially the fact that if in the future you place some stuff as wrappers of your form-groups (like row and cols, for example), you will have there the "hint" why your layout is broken.

**Comment by Enalmada** [comment]
You are a good person for considering the consequences on wrapper users but don't waver from the play-bootstrap spirit...bootstrap specific classes are internal concerns when technically possible.  I am so grateful that play-bootstrap frees me of knowing that form-inline must be exactly on a form-groups container.  I am confident that those who have wrapper issues will be more advanced users likely to immediately consult the play-bootstrap inline form docs when they venture beyond the vanilla defaults.

**Comment by adrianhurt** [comment]
Ok, I think you convinced me… 😆  But I'm not sure about the best way to disable adding the "form-inline" class. I'm thinking in a variable `'_removeDefaultClass` (you all can vote another name for that…) or maybe use `'class` to adding extra classes and `'_class` to override the default class — using an empty string or your own class. I don't know... I prefer not adding more types of field constructors.

**Comment by Enalmada** [comment]
_removeDefaultClass seems sane to me...or _disableDefaultClass.  Just thinking aloud so all options are on the table...you could consider a _defaultClassOverride that could be set to anything like Some("form-custom") or Some("").  You could add @b4.plain.form().

**Comment by adrianhurt** [comment]
Ok, I've just updated the snapshot with `'_disableDefaultClass`. I think it's the easier approach and it let us disabling the default class for any form ("form-vertical", "form-horizontal" and "form-inline")

**Comment by Enalmada** [comment]
One other thing I just noticed is that b4 appears to have changed the way they do "input-group-addon" where you can put icons before and after input elements (https://getbootstrap.com/docs/4.0/components/forms/#auto-sizing).  You may want to update the "Your own custom helpers" part of the docs with the new (input-group-prepend | input-group-append) + input-group-text format for b4.

**Comment by adrianhurt** [comment]
Yes, I noticed it. I'm working on the docs. I hope I can publish them soon. Thanks!!

**Comment by adrianhurt** [comment]
Hi everyone! Just let you know the docs are updated, and not only for version 1.3 but for 1.4 as well (indeed it's not 100% complete for the latter). I finally create a way to passing `'_custom`, `'_feedbackTooltip` and `'_feedbackIcons` arguments to specific form helpers. I think this behaviours should be in the field constructors instead of each helper.

Unfortunately it breaks backward compatibility so now the corresponding field constructors (for vertical, inline and clear forms) are functions instead of values. However the modifications are very easy, but I preferred to release it as a new version.

**Comment by adrianhurt** [comment]
I've just updated the docs to include the B4 custom fields and feedback tooltips. With this, I consider this issue as closed, but feel free to open it again or another one more specific with any doubt, error or bug.

Thank you all!!
